#!/bin/bash
# Disable keyboards (cat protection and such)

# default: detect all keyboards:
props=`xinput --list | awk '/slave/ && /keyboard/' | cut -f2 | cut -c 4`

# Disable keyboards listed in $props
for prop in $props;
do
	newstatus=`expr match 0 $(xinput --list-props $prop | grep "Device Enabled" | cut -f3)`
	xinput set-int-prop $prop "Device Enabled" 8 $newstatus
done
echo "Keyboard status: $newstatus"

# TODO: accept names,numbers as parameters. default = detect keyboards. 
# TODO: detects os, recommend xinput install CL for each distro
