#!/usr/bin/env bash
# Description:	Disable keyboards (for cat protection and such)
# Author:	Benoit Brummer
# Date:		2015-12-27
# License:	GPLv3

# Usage:	./toggleKeyboards
#			Toggle all keyboards
#		./toggleKeyboards <keyboard1> <G710> <keyboardn>
#			Toggle all keyboards that match the input strings

# A list of keyboard names can be found under
#	xinput --list | awk '/slave/ && /keyboard/'

if [ ! -e "/usr/bin/xinput" ]; then
	echo "xinput binary was not found in /usr/bin/xinput."
	if [ ! -z `uname -r | grep ARCH` ]; then
		echo "Install xinput using the following command:"
		echo "	# pacman -S xorg-xinput"
	fi
	exit 1
fi

if [ $# -ne 0 ]; then	# use arguments
	props=()
	for prop in $@;
	do
		props+=`xinput --list | awk "/$prop/ && /slave/ && /keyboard/" | cut -f2 | cut -c 4`
		props=($props)	# separate array w/spaces for accurate count
	done
	
else	# default: detect all keyboards:
	props=`xinput --list | awk '/slave/ && /keyboard/' | cut -f2 | cut -c 4`
fi

# Disable keyboards found in $props
for prop in ${props[@]};
do
	newstatus=`expr match 0 $(xinput --list-props $prop | grep "Device Enabled" | cut -f3)`
	xinput set-int-prop $prop "Device Enabled" 8 $newstatus
	echo "Toggled device $prop, status=$newstatus."
done

if [ ${#props[@]} -eq 0 ]; then
	echo "Nothing happened."
fi
